version: '2.3'
services:
    web:
        image: nginx
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./service:/var/www/task/"
            - "./logs:/var/log/nginx/"
        ports:
            - "0.0.0.0:3002:80"
        restart: always
        depends_on:
            - php
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./service:/var/www/html"
