version: '2.3'
services:
    web:
        image: nginx
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./service:/var/www/task/"
            - "./flag/flag.txt:/opt/flag.txt"
            - "./logs:/var/log/nginx/"
        ports:
            - "0.0.0.0:3002:80"
        restart: always
        depends_on:
            - cgi
    cgi:
        image: wilkesystems/fcgiwrap
        volumes:
            - "./service:/var/www/task"
        restart: always
