version: '2'
services:
  task:
    build: .
    restart: always

  nginx:
    image: nginx
    depends_on:
      - task
    ports:
      - "0.0.0.0:3003:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
